steps:
- name: 'docker' 
  args: ['build','-t','us-central1-docker.pkg.dev/$PROJECT_ID/gcpdevops/img','.']
- name: 'docker'
  args: ['push','us-central1-docker.pkg.dev/$PROJECT_ID/gcpdevops/img']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=gke.yaml
  - --image=us-central1-docker.pkg.dev/$PROJECT_ID/gcpdevops/img
  - --location=us-central1-c
  - --cluster=gke-devops
  - --namespace=gcp-devops-prod