apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gcp-devops-gke
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-devops-gke
  template:
    metadata:
      labels:
        app: gcp-devops-gke
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/tutorials-403317/gcpdevops/img
        name: img
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gcp-devops-gke
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: gcp-devops-gke
  namespace: gcp-devops-prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: gcp-devops-gke
  type: "LoadBalancer"
